module.exports = {
    env: {
        es6: true
    },
    parserOptions: {
        ecmaVersion: 6,
        sourceType: 'module',
        ecmaFeatures: {
            arrowFunctions: true,
            binaryLiterals: true,
            blockBindings: true,
            classes: true,
            defaultParams: true,
            destructuring: true,
            forOf: true,
            generators: true,
            modules: true,
            objectLiteralComputedProperties: true,
            objectLiteralDuplicateProperties: true,
            objectLiteralShorthandMethods: true,
            objectLiteralShorthandProperties: true,
            octalLiterals: true,
            regexUFlag: true,
            regexYFlag: true,
            spread: true,
            superInFunctions: true,
            templateStrings: true,
            unicodeCodePointEscapes: true,
            globalReturn: true
        }
    },
    extends: [
        '../code-style-javascript.js',
        'plugin:import/errors'
    ],
    settings: {
        // Eventually use webpack resolve for finding correct file extensions
        'import/resolver': 'webpack',
        'import/ignore': [
            'node_modules'
        ],
        'import/extensions': [
            '.js',
            '.jsx'
        ]
    },
    rules: {
        'no-console': ['off'],
        'accessor-pairs': ['error'],
        'array-callback-return': ['error'],
        'block-scoped-var': ['error'],
        'consistent-return': ['error'],
        'curly': ['error'],
        'no-array-constructor': ['error'],
        'no-bitwise': ['error'],
        'no-confusing-arrow': ['error'],
        'no-div-regex': ['error'],
        'no-eq-null': ['error'],
        'no-extra-bind': ['error'],
        'no-eval': ['error'],
        'no-implied-eval': ['error'],
        'no-iterator': ['error'],
        'no-loop-func': ['error'],
        'no-native-reassign': ['error'],
        'no-new': ['error'],
        'no-new-func': ['error'],
        'no-new-wrappers': ['error'],
        'no-octal-escape': ['error'],
        'no-proto': ['error'],
        'no-return-assign': ['error'],
        'no-self-compare': ['error'],
        'no-sequences': ['error'],
        'no-shadow-restricted-names': ['error'],
        'no-unmodified-loop-condition': ['error'],
        'no-unsafe-finally': ['error'],
        'no-use-before-define': ['error'],
        'no-void': ['error'],
        'require-yield': ['error'],
        'import/no-commonjs': ['error'],
        'import/no-amd': ['error'],
        'import/no-duplicates': ['error'],
        'import/no-extraneous-dependencies': ['error'],
        'import/no-unresolved': ['off'],
        'no-duplicate-imports': ['error'],
        'brace-style': ['error', '1tbs', {'allowSingleLine': true}],
        'eqeqeq': ['error', 'smart'],
        'guard-for-in': ['error'],
        'no-extend-native': ['error'],
        'wrap-iife': ['error', 'inside'],
        'new-cap': ['error'],
        'no-new-object': ['error'],
        'no-caller': ['error'],
        'no-empty': ['error', {'allowEmptyCatch': true}],
        'no-with': ['error'],
        'no-mixed-spaces-and-tabs': ['error'],
        'indent': ['error', 4, {'SwitchCase': 1}],
        'no-multi-str': ['error'],
        'camelcase': ['error'],
        'no-trailing-spaces': ['error'],
        'comma-spacing': ['error'],
        'keyword-spacing': ['error'],
        'space-before-blocks': ['error'],
        'space-before-function-paren': ['error', 'never'],
        'space-infix-ops': ['error'],
        'space-unary-ops': ['error'],
        'no-undef': ['error'],
        'eol-last': ['warn'],
        'quotes': ['error', 'single'],
        'no-extra-semi': ['error'],
        'no-inner-declarations': ['error'],
        'max-depth': ['error', 5],
        'max-len': ['error', {'code': 300, 'tabWidth': 4}],
        'semi': ['error'],
        'func-style': ['error'],
        'comma-style': ['error']
    }
};
